config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :pregaos, :suppliers, :institutions, :arps, :active_arps
  resources :items do
    resourcers :carts
  end
  get '/wishlist', to: 'carts#wishlist'
  root 'pregaos#index'

end

app/models/active_arp.rb
class ActiveArp < ApplicationRecord
  belongs_to :arp
  belongs_to :item
  belongs_to :institution
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arp.rb
class Arp < ApplicationRecord
  belongs_to :supplier
  belongs_to :pregao
  belongs_to :manager, class_name: 'User'
  belongs_to :manager_sub, class_name: 'User'
  belongs_to :supervisor, class_name: 'User'
  belongs_to :supervisor_sub, class_name: 'User'
  has_many :active_arp

  validates_numericality_of :num_arp, only_integer: true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :active_arp
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :carts
  has_many :active_arp
end

app/models/pregao.rb
class Pregao < ApplicationRecord
  has_many :arps
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :arps
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :manager_arps, class_name: 'Arp', foreign_key: 'manager_id'
  has_many :manager_sub_arps, class_name: 'Arp', foreign_key: 'manager_sub_id'
  has_many :supervisor_arps, class_name: 'Arp', foreign_key: 'supervisor_id'
  has_many :supervisor_sub_arps, class_name: 'Arp', foreign_key: 'supervisor_sub_id'
end

app/controllers/active_arps_controller.rb
class ActiveArpsController < ApplicationController
  before_action :set_active_arp, only: %i[show]
  def index
    @active_arps = ActiveArp.all
  end

  def show; end

  def new
    @active_arp = ActiveArp.new
  end

  def create
    @active_arp = ActiveArp.new(active_arp_params)
    if @active_arp.save
      redirect_to active_arps_path
    else
      render :new
    end
  end

  private

  def active_arp_params
    params.require(:active_arp).permit(:arp_id, :item_id, :item_value, :unit, :qty_item, :date_start, :validity, :institution_id)
  end

  def set_active_arp
    @active_arp = ActiveArp.find(params[:id])
  end
end

app/controllers/arps_controller.rb
class ArpsController < ApplicationController
  before_action :set_arp, only: %i[show edit update]
  def index
    @arps = Arp.all
  end

  def show; end

  def new
    @arp = Arp.new
  end

  def create
    @arp = Arp.new(arp_params)
    if @arp.save
      redirect_to arp_path(@arp)
    else
      render :new
    end
  end

  def edit; end

  def update
    @arp.update(arp_params)
    redirect_to arp_path(@arp)
  end

  private

  def set_arp
    @arp = Arp.find(params[:id])
  end

  def arp_params
    params.require(:arp).permit(:num_arp, :num_sei, :supplier_id, :pregao_id, :manager_id, :manager_sub_id, :supervisor_id, :supervisor_sub_id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: %i[show edit update destroy]
  def index
    @carts = Cart.all
  end

  def show; end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(cart_params)
    if @cart.save
      redirect_to cart_path(@cart)
    else
      render :new
    end
  end

  def edit; end

  def update
    @cart.update(params)
    redirect_to items_path
  end

  def wishlist
    @carts = Cart.where(purchased: false)
  end

  def destroy
    @cart.destroy
    redirect_to items_path
  end

  private

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params.require(:cart).permit(:item_id, :qty_item)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[show edit update destroy]
  def index
    @items = Item.all
  end

  def show; end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path notice: 'Novo item salvo com sucesso.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def destroy
    if @item.destroy
      redirect_to items_path
    else
      redirect_to item_path(@item)
    end
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :category, :catmat, :description, :supply_unit, :area, :group, :sugestion, :critical, :shelf_time, :consuption_year, :price)
  end
end

app/controllers/pregaos_controller.rb
class PregaosController < ApplicationController
  before_action :set_pregao, only: %i[show edit update destroy]

  def index
    @pregaos = Pregao.all
  end

  def show
  end

  def new
    @pregao = Pregao.new
  end

  def create
    @pregao = Pregao.new(pregao_params)
    if @pregao.save
      redirect_to pregaos_path
    else
      render :new
    end
  end

  def edit; end

  def update
    @pregao.update(pregao_params)
    redirect_to pregao_path(@pregao)
  end

  def destroy
    if @pregao.destroy
      redirect_to pregaos_path
    else
      redirect_to pregao_path(@pregao)
    end
  end

  private

  def pregao_params
    params.require(:pregao).permit(:num_pregao, :description)
  end

  def set_pregao
    @pregao = Pregao.find(params[:id])
  end

end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: %i[show edit update destroy]

  def index
    @suppliers = Supplier.all
  end

  def show
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)
    if @supplier.save
      redirect_to supplier_path(@supplier)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @supplier.update(supplier_params)
    redirect_to supplier_path(@supplier)
  end

  def destroy
    if @supplier.destroy
      redirect_to suppliers_path, notice: 'Fornecedor foi removido com sucesso.'
    else
      redirect_to supplier_path(@supplier), alert: 'Fornecedor não foi removido.'
    end
  end

  private

  def supplier_params
    params.require(:supplier).permit(:name, :email, :cnpj)
  end

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end
end

app/helpers/active_arps_helper.rb
module ActiveArpsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arps_helper.rb
module ArpsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pregaos_helper.rb
module PregaosHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/active_arps/_form.html.erb
<%= simple_form_for @active_arp do |f| %>
  <%= f.association :arp, label_method: :num_arp, label: 'ARP' %>
  <%= f.association :item, label: 'Item' %>
  <%= f.input :item_value, as: :currency, label: 'Valor R' %>
  <%= f.input :qty_item, label: 'Quantidade de itens' %>
  <%= f.input :date_start, label: 'Data de início' %>
  <%= f.input :validity, label: 'Validade' %>
  <%= f.association :institution, label: 'Instituição' %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/active_arps/index.html.erb
<h1>ARP Vigentes</h1>

<table>
  <tr>
    <th>ARP</th>
    <th>Item</th>
    <th>Valor do item</th>
    <th>Unidade de apresentação</th>
    <th>Quantidade</th>
    <th>Início da ARP</th>
    <th>Validade</th>
    <th>Instituições</th>
  </tr>
  <tr>
    <% @active_arps.each do |arp| %>
    <td><%= arp.arp.num_arp %></td>
    <td><%= arp.item.name %></td>
    <td><%= arp.item_value %></td>
    <td><%= arp.unit %></td>
    <td><%= arp.qty_item %></td>
    <td><%= arp.date_start %></td>
    <td><%= arp.validity %></td>
    <td><%= arp.institution.name %></td>
    <% end %>
  </tr>
</table>

app/views/active_arps/new.html.erb
<h1>Nova Vigência</h1>

<%= render 'form', active_arp: @active_arp %>

app/views/arps/_form.html.erb
<%= simple_form_for @arp do |f| %>
  <%= f.input :num_arp, label: 'Número ARP' %>
  <%= f.input :num_sei, label: 'Número SEI' %>
  <%= f.association :supplier, label: 'Fornecedor' %>
  <%= f.association :pregao, label_method: :num_pregao, label: 'Pregão' %>
  <%= f.association :manager, label: 'Gestor' %>
  <%= f.association :manager_sub, label: 'Gestor substituto' %>
  <%= f.association :supervisor, label: 'Fiscal' %>
  <%= f.association :supervisor_sub, label: 'Fiscal substituto' %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/arps/edit.html.erb
<h1>Editar ARP <%= @arp.num_arp %></h1>

<%= render 'form', arp: @arp %>

app/views/arps/index.html.erb
<h1>Atas de Registro de Preço</h1>

<table>
  <tr>
    <th>Número ARP</th>
    <th>Número SEI</th>
    <th>Fornecedor</th>
    <th>Pregão</th>
    <th>Gestor</th>
    <th>Gestor Substituto</th>
    <th>Fiscal</th>
    <th>Fiscal Substituto</th>
  </tr>
  <tr>
    <%= @arps.each do |arp| %>
    <td><%= arp.num_arp %></td>
    <td><%= arp.num_sei %></td>
    <td><%= arp.supplier.name %></td>
    <td><%= arp.pregao.num_pregao %></td>
    <td><%= arp.manager.name %></td>
    <td><%= arp.manager_sub.name %></td>
    <td><%= arp.supervisor.name %></td>
    <td><%= arp.supervisor_sub.name %></td>
    <% end %>
  </tr>
  <%= @arps.each do |arp| %>
  <li><%= arp.num_arp %></li>
  <% end %>
</table>

app/views/arps/new.html.erb
<h1>Nova Ata de Registro de Preços</h1>

<%= render 'form', arp: @arp %>

app/views/arps/show.html.erb
<h1>Ata de Registro de Preços <%= @arp.num_arp %></h1>

<p>SEI: <%= @arp.num_sei %></p>
<p>Fornecedor: <%= @arp.supplier.name %></p>
<p>Pregão: <%= @arp.pregao.num_pregao %></p>
<p>Gestor: <%= @arp.manager.name %></p>
<p>Gestor substituto: <%= @arp.manager_sub.name %></p>
<p>Fiscal: <%= @arp.supervisor.name %></p>
<p>Fiscal substituto: <%= @arp.supervisor_sub.name %></p>

app/views/carts/_form.html.erb
<%= simple_form_for @cart do |f| %>
  <%= f.association :item %>
  <%= f.input :qty_item, label: 'Quantidade' %>
  <%= f.submit 'Pedir' %>
<% end %>

app/views/carts/edit.html.erb
<h1>Editar pedido</h1>

<%= render 'form', cart: @cart %>

app/views/carts/index.html.erb
<h1>Pedidos</h1>

<div>
  <ul>
    <% @carts.each do|i| %>
      <li><%= i.id %>: <%= i.item.name %> - <%= i.qty_item %> | Alterar quantidade | <%= link_to 'Excluir solicitação', cart_path(i), data: {turbo_method: :delete, turbo_confirm: 'Confirma?'} %> </li>
    <% end %>
  </ul>
</div>

app/views/carts/new.html.erb
<h1>Novo pedido</h1>

<%= render 'form', cart: @cart %>

app/views/carts/show.html.erb
<h1>Pedido <%= @cart.id %></h1>

<p>Item: <%= @cart.item.name %> - Quantidade: <%= @cart.qty_item %> | Alterar quantidade | <%= link_to 'Excluir solicitação', cart_path(@cart), data: {turbo_method: :delete, turbo_confirm: 'Confirma?'} %></p>

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |i| %>
  <%= i.input :name, label: 'Nome' %>
  <%= i.input :category, label: 'Categoria' %>
  <%= i.input :catmat, label: 'CATMAT' %>
  <%= i.input :description, label: 'Descrição' %>
  <%= i.input :supply_unit, label: 'Unidade de fornecimento' %>
  <%= i.input :area, label: 'Área' %>
  <%= i.input :group, label: 'Grupo' %>
  <%= i.input :sugestion, label: 'Sugestão' %>
  <%= i.input :critical, label: 'É crítico?' %>
  <%= i.input :shelf_time, label: 'Tempo de prateleira' %>
  <%= i.input :consuption_year, label: 'Consumo anual' %>
  <%= i.input :price, label: 'Preço (estimado)' %>
  <%= i.submit 'Salvar' %>
<% end %>

app/views/items/edit.html.erb
<h1>Editar Item</h1>

<div>
  <%= render 'form', item: @item %>
</div>

app/views/items/index.html.erb
<h1>Itens</h1>

<ul>
  <% @items.each do |i| %>
    <li><%= i.category %> - <%= link_to "#{i.name}", item_path(i) %> | Adicionar ao pedido</li>
  <% end %>
</ul>

app/views/items/new.html.erb
<h1>Novo Item</h1>

<div>
  <%= render 'form', item: @item %>
</div>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>
<h2>Descrição: <%= @item.description %></h2>
<p>CATMAT: <%= @item.catmat %></p>
<p>Crítico? <%= @item.critical %></p>
<p>Adicionar ao pedido</p>

app/views/pregaos/_form.html.erb
<%= simple_form_for(pregao) do |f| %>
  <%= f.input :num_pregao %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/pregaos/edit.html.erb
<h1>Editar Pregão <%= @pregao.num_pregao %></h1>

<p>
  <%= render 'form', pregao: @pregao %>
</p>
<p>
  <%= link_to 'Mostrar pregões salvos', pregaos_path %>
</p>

app/views/pregaos/index.html.erb
<h1>Pregões</h1>

<ul>
  <% @pregaos.each do |p| %>
    <li><%= link_to "#{p.num_pregao}", pregao_path(p) %> - <%= p.description %></li>
  <% end %>
</ul>

app/views/pregaos/new.html.erb
<h1>Novo Pregão</h1>

<p>
  <%= render 'form', item: @item %>
</p>
<p>
  <%= link_to 'Mostrar pregões salvos', pregaos_path %>
</p>

app/views/pregaos/show.html.erb
<h1>Pregao <%= @pregao.id %></h1>

<p>Pregão número <%= @pregao.num_pregao %>.</p>
<h3>Descrição</h3>
<p><%= @pregao.description %></p>

<%= link_to 'Excluir pregão', pregao_path(@pregao), data: {turbo_method: :delete, turbo_confirm: 'Confirma?'} %>

app/views/suppliers/_form.html.erb
<%= simple_form_for(supplier) do |f| %>
  <%= f.input :name, label: 'Fornecedor' %>
  <%= f.input :email, label: 'e-mail' %>
  <%= f.input :cnpj, label: 'CNPJ' %>
  <%= f.submit 'Salvar' %>
<% end %>

app/views/suppliers/edit.html.erb
<h1>Editar informações do fornecedor <%= @supplier.name %></h1>

<%= render 'form', supplier: @supplier %>

app/views/suppliers/index.html.erb
<h1>Fornecedores</h1>

<h3><%= link_to 'Cadastrar novo fornecedor', new_supplier_path %></h3>

<ul>
  <% @suppliers.each do |s| %>
    <li><%= s.id %> - <%= link_to "#{s.name}", supplier_path(s) %> | <%= s.email %> | <%= s.cnpj %></li>
  <% end %>
</ul>

app/views/suppliers/new.html.erb
<h1>Cadastro de fornecedor</h1>

<%= render 'form', supplier: @supplier %>

<p>
  <%= link_to 'Lista de fornecedores', suppliers_path %>
  </p>

app/views/suppliers/show.html.erb
<h1>Fornecedor <%= @supplier.name %></h1>

<p>e-mail:<%= @supplier.email %></p>
<p>CNPJ <%= @supplier.cnpj %></p>

<p><%= link_to 'Editar fonecedor', edit_supplier_path(@supplier) %></p>
<p><%= link_to 'Excluir fornecedor', supplier_path(@supplier), data: {turbo_method: :delete, turbo_confirm: 'Confirma?'} %></p>